In [1]:
import queue
import numpy as np

In [280]:
class graph:
    def __init__(self, name, adj_list=None, weights=None, adj_matrix= None):
        self.name = name
        self.adj_list=  adj_list
        self.weights = weights
        if self.adj_list != None:
            self.nnodes = len(adj_list)
            self.visited = [False] * self.nnodes
            self.components = [None] * self.nnodes
            self.count = 0
    #def add_node(self, adj_list):
    def dfs(self, at):
        self.visited = [False] * self.nnodes
        self.vorder = []
        res = self.dfs_run(at)
        return res
        print('323223')
    def dfs_run(self, at):
        #print(at, self.visited)
        self.components[at] = self.count
        if not self.visited[at]:
            self.visited[at] = True
            self.vorder.append(at)
            neighbors = self.adj_list[at]
            for nextn in neighbors:
                if not self.visited[nextn]:
                    self.dfs_run(nextn)
#         self.visited = [False] * self.nnodes
        return self.vorder
    
    def findComponents(self):
        self.visited = [False]* self.nnodes
        for i in range(self.nnodes):
            if not self.visited[i]:
                self.count += 1
                self.dfs(i)
        return (self.count, self.components)
    
    def bfs(self,s,e):
        prev = self.solve(s)
        return self.reconstruct(s,e,prev)
    def solve(self,s):
        q = queue.Queue()
        q.put(s)
        visited= [False] * self.nnodes
        visited[s] = True
        prev = [None]*self.nnodes
        
        while not q.empty():
            node = q.get()
            neighbours = self.adj_list[node]
            
            for nextn in neighbours:
                if not visited[nextn]:
                    q.put(nextn)
                    visited[nextn] = True
                    prev[nextn] = node
        print(prev)
        return prev
    
    def reconstruct(self,s,e,prev):
        path = []
        at = e
        while at!=None:
            at = prev[at]
            path.append(at)
        path.reverse()
        return path
#         if path[0] == s:
#             return path
#         else:
#             return []
    
    def bfs2(self,s,e):
        visited= [False] * self.nnodes
        q = queue.Queue()
        q.put(s)
        visited[s] = True
        while not q.empty():
            node = q.get()
            print(node,end =" ")
            for neighbours in self.adj_list[node]:
                if not visited[neighbours] :
                    visited[neighbours] = True
                    q.put(neighbours)
        return visited
                
    def __str__(self):
        return str(self.name)                

    def top_finder(self,g2,v):
        f = [i for i in range(len(g2))]
        for i in range(len(g2)):
            for j in g2:
                if (i in j) or v[i]:
                    f.remove(i)
                    break
        return f,v
    def topological_sort(self):
        f_list = []
        visited = [False] * self.nnodes
        count = 0
        gg = self.adj_list.copy()
        for j in range(len(gg)):
            b,visited = top_finder(gg,visited)
            for father in b:
                gg[father] = []
                visited[father] = True
            if len(b)>0:
                f_list.append(b)
        return f_list
    
    def shortest_path(self):
        path_value = [float('inf')] * self.nnodes
        path_value[0] = 0
        at = 0
        top_sort= self.topological_sort()
        prevs = [0]
        for nodes in range(1,len(top_sort)):
            for node in top_sort[nodes]:
                for prev_node in prevs:
                    if (prev_node,node) in self.weights:
                        w = self.weights[(prev_node,node)]
                        w += path_value[prev_node]
                        path_value[node] = min(w, path_value[node])
                prevs.append(node)
                        
        return path_value

     

In [22]:
class dengeun(graph):
    def create_dngs(self,dng,r,c):
        self.adj_matrix = np.zeros([r,c])
        dngns_r = np.random.randint(0,r,dng)
        dngns_c = np.random.randint(0,c,dng)
#         while (start[0] in dngns_r and finish[0] in dngns_r) and (start[1] in dngns_c and finish[1] in dngns_c):
#             dngns_r = np.random.randint(0,r,dng)
#             dngns_c = np.random.randint(0,c,dng)
        self.adj_matrix[dngns_r,dngns_c] = -1
#         self.adj_matrix[start[0],start[1]] = 1
#         self.adj_matrix[finish[0],finish[1]] = 2
        return self.adj_matrix
    
    def solve_dng(self,start, finish):
        start = np.array(start)
        finish = np.array(finish)
        visited = np.full_like(self.adj_matrix,fill_value=False)
        prev = np.full([self.adj_matrix.shape[0],self.adj_matrix.shape[1],1,2], fill_value=None)
        visited[start[0],start[1]] = True
        qr = queue.Queue()
        qc = queue.Queue()
        qr.put(start[0])
        qc.put(start[1])
        dr = [-1,1,0,0]
        dc = [0,0,1,-1]

        #explore neighbours and put in queues
        at = np.array(start)
        while not all(at == finish):
            if not qr.empty():
                at[0] = qr.get()
                at[1] = qc.get()
            #print("now at:",at)
            for i in range(len(dr)):
                nextn = at + np.array([dr[i],dc[i]])
                if nextn[0]>=0 and nextn[0]<self.adj_matrix.shape[0] and nextn[1]>=0 and nextn[1]<self.adj_matrix.shape[1]:
                    if (self.adj_matrix[nextn[0], nextn[1]] != -1) and not visited[nextn[0], nextn[1]]:
                        #print("next is ",nextn)
                        qr.put(nextn[0])
                        qc.put(nextn[1])
                        visited[nextn[0],nextn[1]] = True
                        prev[nextn[0],nextn[1]] = at
                        #at = nextn
        #print("prev is ", prev)
        #reconstruct
        #print(prev)
        back = prev[finish[0], finish[1],0,:]
        path = []
        path.append(back)
        #print('next step', prev[back[0],back[1]])
        while not all(back == start):
            #print('next step', prev[back[0],back[1]])
            back = prev[back[0],back[1],0,:]
            path.append(back)
        path.reverse()   
        return path
                    
        
        

        
    

True

In [23]:
g4 = dengeun('dngn')
print(g4)

dngn


In [24]:
g4.create_dngs(3,5,5)

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -1.,  0.,  0.]])

In [25]:
g4.solve_dng([1,2],[4,4])

[array([1, 2], dtype=object),
 array([2, 2], dtype=object),
 array([3, 2], dtype=object),
 array([3, 3], dtype=object),
 array([4, 3], dtype=object)]

In [276]:
g4.create_dngs(0,5,7)
g4.adj_matrix[[0,1,1,2,3,3,4,4,4],[3,1,5,1,2,3,0,2,5]] = -1

In [277]:
g4.solve_dng([0,0],[4,3])

[array([4, 4], dtype=object),
 array([3, 4], dtype=object),
 array([2, 4], dtype=object),
 array([2, 3], dtype=object),
 array([2, 2], dtype=object),
 array([1, 2], dtype=object),
 array([0, 2], dtype=object),
 array([0, 1], dtype=object),
 array([0, 0], dtype=object)]

In [218]:
adj1 = [[1], [2,3],[1],[1], [5,6],[4],[4],[7]]

In [260]:
adj2 =[[1],[2,3],[5],[4],[7],[6],[7],[8], []]
w2 = {
    (0,1):1,
    (1,2):2,
    (1,3):1,
    (3,4):-1,
    (4,7):4,
    (7,8):1,
    (6,4):2,
    (5,6):1,
    (2,5):3
}
# w2 = {
#     0:[(1,1)],
#     1:[(2,2),(3,1)],
#     2:[(5,3)],
#     3:[(4,-1)],
#     4:[(7,4)],
#     5:[(6,1)],
#     6:[(7,2)],
#     7:[(8,1)]
# }

In [230]:
(0,3) in w2

False

In [189]:
a = [[1,2],[],[3,4],[5,6],[7],[1],[],[6]]

In [209]:

# a = adj2.copy()

def top_finder(g2,v):
    f = [i for i in range(len(g2))]
    for i in range(len(g2)):
        for j in g2:
            if (i in j) or v[i]:
                f.remove(i)
                break
    return f,v
def top_path(g):
    f_list = []
    visited = [False] * len(g)
    count = 0
    gg = g.copy()
    for j in range(len(gg)):
        b,visited = top_finder(gg,visited)
        for father in b:
            gg[father] = []
            visited[father] = True
        if len(b)>0:
            f_list.append(b)
    return f_list
    
father_path(adj2)    

[[0], [1], [2, 3], [4, 5], [6], [7], [8]]

In [203]:
a

[[1, 2], [], [3, 4], [5, 6], [7], [1], [], [6]]

In [186]:
adj3 = adj2.copy()


In [187]:
type(ajd)

[[1], [2, 3], [5], [4], [7], [6], [7], [8], []]

In [164]:
adj3

[[1], [2, 3], [], [4], [7], [6], [7], [8], []]

In [264]:
g2 = graph('g2', adj2,weights=w2)

In [265]:
g2.shortest_path(0,8)

[0, 1, 3, 2, 1, 6, 7, 5, 6]

In [247]:
g2.topological_sort()

[[0], [1], [2, 3], [4, 5], [6], [7], [8]]

In [213]:
g2.top_path()

[[0], [1], [2, 3], [4, 5], [6], [7], [8]]

In [219]:
g1 = graph('g1', adj1)

In [220]:
g1.topological_sort()

[[0]]

In [48]:
g1.findComponents()

0 [False, False, False, False, False, False, False, False]
1 [True, False, False, False, False, False, False, False]
2 [True, True, False, False, False, False, False, False]
3 [True, True, True, False, False, False, False, False]
4 [True, True, True, True, False, False, False, False]
5 [True, True, True, True, True, False, False, False]
6 [True, True, True, True, True, True, False, False]
7 [True, True, True, True, True, True, True, False]


(3, [1, 1, 1, 1, 2, 2, 2, 3])

In [66]:
g2.dfs(0)

0 [False, False, False, False, False, False, False, False, False]
1 [True, False, False, False, False, False, False, False, False]
2 [True, True, False, False, False, False, False, False, False]
5 [True, True, True, False, False, False, False, False, False]
6 [True, True, True, False, False, True, False, False, False]
7 [True, True, True, False, False, True, True, False, False]
4 [True, True, True, False, False, True, True, True, False]
3 [True, True, True, False, True, True, True, True, False]
8 [True, True, True, True, True, True, True, True, False]


[True, True, True, True, True, True, True, True, True]

In [67]:
g2.findComponents()

0 [False, False, False, False, False, False, False, False, False]
1 [True, False, False, False, False, False, False, False, False]
2 [True, True, False, False, False, False, False, False, False]
5 [True, True, True, False, False, False, False, False, False]
6 [True, True, True, False, False, True, False, False, False]
7 [True, True, True, False, False, True, True, False, False]
4 [True, True, True, False, False, True, True, True, False]
3 [True, True, True, False, True, True, True, True, False]
8 [True, True, True, True, True, True, True, True, False]


(1, [1, 1, 1, 1, 1, 1, 1, 1, 1])

In [253]:
adj3 = [
    [1,2,9],
    [0,6,3,4],
    [0,5],
    [1,7,8],
    [1],
    [2],
    [1],
    [3],
    [3,9],
    [0,8]
]

In [59]:
g3 = graph('g3', adj3)

In [61]:
g3.bfs(5,8)

[2, 0, 5, 1, 1, None, 1, 3, 9, 0]


[None, 5, 2, 0, 9]

In [37]:
print(g3)

g3


In [277]:
adj4= [
    [1,2],
    [5,3],
    [3,4],
    [4],
    []
]
w4= {
    (0,1):1,
    (0,2):2,
    (1,5):1,
    (1,3):3,
    (2,3):-1,
    (2,4):2,
    (3,4):3
}

In [281]:
g4 = graph('g4', adj4,w4)

In [282]:
g4.shortest_path()

[0, 1, 2, 1, 4]